name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: make install

    - name: Unit tests
      run: coverage run -m unittest discover test

    - name: Generate coverage report
      run: coverage report -m

    # Run these ? Check and distcheck
    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
